# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

index:
   path: /
   defaults: { _controller: 'Controller\DefaultController::indexAction' }

produit:
   path: /produit/{id}
   defaults: { _controller: 'Controller\DefaultController::produitAction' }

expo:
   path: /expo/{id}
   defaults: { _controller: 'Controller\DefaultController::expoAction' }

jeuredirect:
   path: /jeuredirect
   defaults: { _controller: 'Controller\DefaultController::jeuredirectAction' }

jeu:
   path: /jeu/{id}
   defaults: { _controller: 'Controller\DefaultController::jeu' }


jeuupload:
   path: /jeu/{id}/upload
   defaults: { _controller: 'Controller\DefaultController::upload' }

createmetacasquette:
   path: /jeu/{id}/createmetacasquette
   defaults: { _controller: 'Controller\DefaultController::createmetacasquette' }

getRandomGenerated:
   path: /jeu/{id}/randomgenerated
   defaults: { _controller: 'Controller\DefaultController::randomgenerated' }

adminList:
   path: /admin/list
   defaults: { _controller: 'Controller\AdminController::adminListAction' }

adminEdit:
   path: /admin/edit/{id}
   defaults: { _controller: 'Controller\AdminController::adminEditAction' }

adminImages:
   path: /admin/images/{id}
   defaults: { _controller: 'Controller\AdminController::adminImagesAction' }

adminAdd:
   path: /admin/add
   defaults: { _controller: 'Controller\AdminController::adminAddAction' }

adminCsv:
   path: /admin/csv/list/{fileName}
   defaults: { _controller: 'Controller\AdminController::adminCsvListAction' }
