# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    env(APP_TELEPHONE): ''
    env(APP_EMAIL): ''
    env(APP_FACEBOOK): ''
    env(APP_INSTAGRAM): ''
    env(APP_YTID): ''
    env(APP_PATHFILES): '%kernel.project_dir%/data'
    env(APP_GAMEURL): '/'
    env(APP_OPENAIKEY): ''
    env(APP_GOOGLEAPIFILE): ''

    app.telephone: '%env(APP_TELEPHONE)%'
    app.email: '%env(APP_EMAIL)%'
    app.facebook: '%env(APP_FACEBOOK)%'
    app.instagram: '%env(APP_INSTAGRAM)%'
    app.ytid: '%env(APP_YTID)%'
    app.pathFiles: '%env(APP_PATHFILES)%'
    app.gameurl: '%env(APP_GAMEURL)%'
    app.openaikey: '%env(APP_OPENAIKEY)%'
    app.googleapifile: '%env(APP_GOOGLEAPIFILE)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.
    get_set_method_normalizer:
        class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
        public: false
        tags: [serializer.normalizer]

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Service\CatalogueCsvService:
        arguments:
            - '%app.pathFiles%'
            - '%kernel.project_dir%'

    App\Command\SyncCatalogueDatabaseCommand:
        tags:
            - { name: 'console.command', command: 'app:catalog:sync-db' }

    App\Service\CreationRateLimiter:
        arguments:
            $directory: '%kernel.project_dir%/var/creation-rate-limits'
